name: Build and Deploy to Netlify

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: false

            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Init needed submodules
              run: |
                  git submodule update --init packages/ui
                  git submodule update --init apps/app

            - name: Install dependencies
              run: bun install -D netlify-cli

            - name: Build project
              run: bunx turbo run build --filter="./packages/ui" --filter="./apps/app"

            # Deploy to Netlify (using Netlify CLI)
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              run: bunx netlify deploy --prod --site=94e51d96-ca0f-4128-bda5-7f22eb07fcc5 --dir=apps/app/dist
