name: Build and Deploy to Netlify

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  submodules: "false"

            - name: Init needed submodules
              run: |
                  git submodule update --init packages/ui
                  git submodule update --init apps/app

            - name: Install dependencies
              run: bun install

            - name: Build project
              run: bun run build

            # Deploy to Netlify (using Netlify CLI)
            - name: Deploy to Netlify
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
              run: npx netlify deploy --prod --site=94e51d96-ca0f-4128-bda5-7f22eb07fcc5 --dir=apps/app/dist
